function [trainedClassifier, validationAccuracy] = trainClassifier_Midterm(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double containing the accuracy in percent. In
%       the app, the History list displays this overall accuracy score for
%       each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   yfit = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 10-Dec-2021 10:48:04


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'median_acc_z', 'rms_acc_x', 'var_acc_y', 'specCentroid_rate_z', 'specCentroid_acc_y', 'mean_acc_z', 'median_rate_y', 'std_rate_z', 'rms_rate_z', 'median_rate_x', 'std_acc_y', 'var_rate_z', 'std_acc_x', 'std_rate_y', 'rms_rate_y', 'rms_norm_acc', 'var_acc_x', 'specCentroid_rate_y', 'rms_norm_rate', 'mean_norm_acc', 'mean_norm_rate', 'specCentroid_acc_z', 'median_norm_rate', 'std_norm_acc', 'var_rate_y', 'var_norm_acc', 'std_norm_rate', 'median_norm_acc', 'rms_acc_y', 'std_rate_x', 'median_acc_x', 'rms_rate_x', 'std_acc_z', 'median_rate_z', 'var_norm_rate', 'mean_rate_y', 'specCentroid_acc_x', 'specCentroid_rate_x', 'var_rate_x'};
predictors = inputTable(:, predictorNames);
response = inputTable.features_type;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
template = templateSVM(...
    'KernelFunction', 'polynomial', ...
    'PolynomialOrder', 3, ...
    'KernelScale', 'auto', ...
    'BoxConstraint', 1, ...
    'Standardize', true);
classificationSVM = fitcecoc(...
    predictors, ...
    response, ...
    'Learners', template, ...
    'Coding', 'onevsone', ...
    'ClassNames', {'downStep'; 'flat'; 'upStep'});

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
svmPredictFcn = @(x) predict(classificationSVM, x);
trainedClassifier.predictFcn = @(x) svmPredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'mean_acc_z', 'mean_norm_acc', 'mean_norm_rate', 'mean_rate_y', 'median_acc_x', 'median_acc_z', 'median_norm_acc', 'median_norm_rate', 'median_rate_x', 'median_rate_y', 'median_rate_z', 'rms_acc_x', 'rms_acc_y', 'rms_norm_acc', 'rms_norm_rate', 'rms_rate_x', 'rms_rate_y', 'rms_rate_z', 'specCentroid_acc_x', 'specCentroid_acc_y', 'specCentroid_acc_z', 'specCentroid_rate_x', 'specCentroid_rate_y', 'specCentroid_rate_z', 'std_acc_x', 'std_acc_y', 'std_acc_z', 'std_norm_acc', 'std_norm_rate', 'std_rate_x', 'std_rate_y', 'std_rate_z', 'var_acc_x', 'var_acc_y', 'var_norm_acc', 'var_norm_rate', 'var_rate_x', 'var_rate_y', 'var_rate_z'};
trainedClassifier.ClassificationSVM = classificationSVM;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2020b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'median_acc_z', 'rms_acc_x', 'var_acc_y', 'specCentroid_rate_z', 'specCentroid_acc_y', 'mean_acc_z', 'median_rate_y', 'std_rate_z', 'rms_rate_z', 'median_rate_x', 'std_acc_y', 'var_rate_z', 'std_acc_x', 'std_rate_y', 'rms_rate_y', 'rms_norm_acc', 'var_acc_x', 'specCentroid_rate_y', 'rms_norm_rate', 'mean_norm_acc', 'mean_norm_rate', 'specCentroid_acc_z', 'median_norm_rate', 'std_norm_acc', 'var_rate_y', 'var_norm_acc', 'std_norm_rate', 'median_norm_acc', 'rms_acc_y', 'std_rate_x', 'median_acc_x', 'rms_rate_x', 'std_acc_z', 'median_rate_z', 'var_norm_rate', 'mean_rate_y', 'specCentroid_acc_x', 'specCentroid_rate_x', 'var_rate_x'};
predictors = inputTable(:, predictorNames);
response = inputTable.features_type;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Perform cross-validation
partitionedModel = crossval(trainedClassifier.ClassificationSVM, 'KFold', 5);

% Compute validation predictions
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);

% Compute validation accuracy
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');
